name: Docker

on:
  push:
  schedule:
  # every day
    - cron: '0 1 * * *'

env:
  REGISTRY: ghcr.io
  REGISTRY_BASE_PATH: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: Build and publish images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout sydent code
        uses: actions/checkout@v2
        with:
          repository: 'matrix-org/sydent'
          ref: 'dinsic'

      - name: Calculate docker image tag
        id: set-tag
        run: |
          git fetch -t
          tag=$( git describe --tags --always)
          echo "::set-output name=tag::$tag"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY_BASE_PATH }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: "${{ env.REGISTRY_BASE_PATH }}:${{ steps.set-tag.outputs.tag }}, ${{ env.REGISTRY_BASE_PATH }}:latest"
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: true
